# Form implementation generated from reading ui file 'fakt.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 751)
        MainWindow.setMinimumSize(QtCore.QSize(0, 100))
        MainWindow.setStyleSheet("QMainWindow{\n"
"\n"
"    background-color: rgb(108, 108, 108)\n"
"\n"
"}\n"
"\n"
"\n"
"#num_Invoke {\n"
"    border : 2px solid #BDEEFF;\n"
"background-color:#BDEEFF;\n"
"font: 700 italic 10pt \"Book Antiqua\";\n"
"border-radius:6px;\n"
"padding: 3px\n"
"\n"
"\n"
"}\n"
"\n"
"#num_Invoke:hover {\n"
"border: 2px solid SlateBlue\n"
"\n"
"}\n"
"\n"
"#num_Invoke:focus {\n"
"background-color:  SlateBlue\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"\n"
"\n"
"background-color: SlateBlue;\n"
"color: white\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"background: qlineargradient(\n"
"x1:0, y1:0 ,x2:0, y2:1,\n"
"stop: 0 #87CEEB,\n"
"stop:1 #000080\n"
")\n"
"}")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(570, 20, 91, 20))
        self.label_12.setStyleSheet("font: 700 12pt \"Arial\";")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.num_Invoke = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.num_Invoke.setGeometry(QtCore.QRect(660, 20, 132, 21))
        self.num_Invoke.setStyleSheet("")
        self.num_Invoke.setText("")
        self.num_Invoke.setPlaceholderText("")
        self.num_Invoke.setObjectName("num_Invoke")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(280, -10, 321, 81))
        self.label_14.setStyleSheet("font: 30px \",,Fixedsys\";\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(90, 80, 331, 211))
        self.frame_3.setStyleSheet("#frame_3 {\n"
"                background-color: rgb(160, 160, 160);\n"
"border: 2px solid #CCCCCC;\n"
"padding: 6px;\n"
"border-radius: 6px\n"
"\n"
"}\n"
"\n"
"QLineEdit { \n"
"border: none;\n"
"border-bottom: 2px dashed  #6c6c6c;\n"
"background: transparent;\n"
"padding: 2px;\n"
"font: 700 italic 10pt \"Book Antiqua\";\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover {\n"
"border-bottom: 2px dashed SlateBlue\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus {\n"
"border-bottom: 2px solid SlateBlue\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QLabel {\n"
"        font: 700 italic 10pt \"Book Antiqua\";\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 20, 241, 192))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_16.addWidget(self.label_10)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_17 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet("QVBoxLayout {\n"
"    color: \"red\"\n"
"}")
        self.label_17.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.verticalLayout_16.addLayout(self.verticalLayout_17)
        self.label_23 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_16.addWidget(self.label_23)
        self.label_26 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_26.setStyleSheet("")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_16.addWidget(self.label_26)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.supplier_name = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.supplier_name.setPlaceholderText("")
        self.supplier_name.setObjectName("supplier_name")
        self.verticalLayout_5.addWidget(self.supplier_name)
        self.supplier_address = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.supplier_address.setObjectName("supplier_address")
        self.verticalLayout_5.addWidget(self.supplier_address)
        self.supplier_town = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.supplier_town.setStyleSheet("#lineEdit_4 { \n"
"border: none;\n"
"border-bottom: 2px dashed grey;\n"
"background: transparent;\n"
"padding: 2px\n"
"\n"
"\n"
"\n"
"}")
        self.supplier_town.setObjectName("supplier_town")
        self.verticalLayout_5.addWidget(self.supplier_town)
        self.supplier_PN = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.supplier_PN.setObjectName("supplier_PN")
        self.verticalLayout_5.addWidget(self.supplier_PN)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_27 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_10.addWidget(self.label_27)
        self.supplier_ICO = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.supplier_ICO.setObjectName("supplier_ICO")
        self.horizontalLayout_10.addWidget(self.supplier_ICO)
        self.label_28 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_28.setIndent(0)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_10.addWidget(self.label_28)
        self.supplier_DIC = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.supplier_DIC.setObjectName("supplier_DIC")
        self.horizontalLayout_10.addWidget(self.supplier_DIC)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(90, 310, 691, 101))
        self.frame_4.setStyleSheet("#frame_4 {     background-color: rgb(160, 160, 160);\n"
"border: 2px solid #CCCCCC;\n"
"padding: 6px;\n"
"border-radius: 6px\n"
" }\n"
"\n"
"\n"
"QLabel {\n"
"    \n"
"    font: 700 italic 10pt \"Book Antiqua\";\n"
"border:none\n"
"}\n"
" QLineEdit {\n"
"    background-color:#BDEEFF;\n"
"font: 700 italic 10pt \"Book Antiqua\";\n"
"border-radius: 6px;\n"
"padding: 3px\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid SlateBlue;\n"
"border-radius: 6px\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"background-color:  SlateBlue;\n"
"border-radius: 6px;\n"
"border: 2px solid #BDEEFF\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 10, 561, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.bank_acc = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.bank_acc.setObjectName("bank_acc")
        self.verticalLayout_2.addWidget(self.bank_acc)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.issue_date = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.issue_date.setObjectName("issue_date")
        self.verticalLayout.addWidget(self.issue_date)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.due_date = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.due_date.setObjectName("due_date")
        self.verticalLayout_3.addWidget(self.due_date)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.payment_method = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.payment_method.setPlaceholderText("")
        self.payment_method.setObjectName("payment_method")
        self.verticalLayout_6.addWidget(self.payment_method)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(450, 80, 331, 211))
        self.frame_5.setStyleSheet("#frame_5 {\n"
"                background-color: rgb(160, 160, 160);\n"
"border: 2px solid #CCCCCC;\n"
"padding: 6px;\n"
"border-radius: 6px\n"
"\n"
"}\n"
"\n"
"QLineEdit { \n"
"border: none;\n"
"border-bottom: 2px dashed  #6c6c6c;\n"
"background: transparent;\n"
"padding: 2px;\n"
"font: 700 italic 10pt \"Book Antiqua\";\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover {\n"
"border-bottom: 2px dashed SlateBlue\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus {\n"
"border-bottom: 2px solid SlateBlue\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QLabel {\n"
"        font: 700 italic 10pt \"Book Antiqua\";\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.frame_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 20, 241, 192))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_19.addWidget(self.label_11)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_18 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setStyleSheet("QVBoxLayout {\n"
"    color: \"red\"\n"
"}")
        self.label_18.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_20.addWidget(self.label_18)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.label_24 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_19.addWidget(self.label_24)
        self.label_29 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_29.setStyleSheet("")
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_19.addWidget(self.label_29)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.customer_name = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.customer_name.setPlaceholderText("")
        self.customer_name.setObjectName("customer_name")
        self.verticalLayout_7.addWidget(self.customer_name)
        self.customer_address = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.customer_address.setObjectName("customer_address")
        self.verticalLayout_7.addWidget(self.customer_address)
        self.customer_town = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.customer_town.setStyleSheet("#lineEdit_4 { \n"
"border: none;\n"
"border-bottom: 2px dashed grey;\n"
"background: transparent;\n"
"padding: 2px\n"
"\n"
"\n"
"\n"
"}")
        self.customer_town.setObjectName("customer_town")
        self.verticalLayout_7.addWidget(self.customer_town)
        self.customer_PN = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.customer_PN.setObjectName("customer_PN")
        self.verticalLayout_7.addWidget(self.customer_PN)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_18.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_30 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_12.addWidget(self.label_30)
        self.customer_ICO = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.customer_ICO.setObjectName("customer_ICO")
        self.horizontalLayout_12.addWidget(self.customer_ICO)
        self.label_31 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_31.setIndent(0)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_12.addWidget(self.label_31)
        self.customer_DIC = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        self.customer_DIC.setObjectName("customer_DIC")
        self.horizontalLayout_12.addWidget(self.customer_DIC)
        self.verticalLayout_18.addLayout(self.horizontalLayout_12)
        self.calc_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.calc_table.setGeometry(QtCore.QRect(90, 440, 691, 161))
        self.calc_table.setStyleSheet("\n"
"\n"
"QTableWidget {\n"
"background-color: rgb(160, 160, 160);\n"
"border: 2px solid #CCCCCC;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: SlateBlue;\n"
"color:white;\n"
"padding: 6px 8px;\n"
"border:none\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    \n"
"    background-color:  #6c6c6c\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    \n"
"    background:transparent\n"
"    }\n"
"QTableWidget QLineEdit {\n"
"border:none;\n"
"background:transparent\n"
"\n"
"}\n"
"\n"
"QTableCornerButton::section{\n"
"background-color: SlateBlue;\n"
"}\n"
"")
        self.calc_table.setShowGrid(False)
        self.calc_table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.calc_table.setObjectName("calc_table")
        self.calc_table.setColumnCount(5)
        self.calc_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        item.setFont(font)
        self.calc_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.calc_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.calc_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.calc_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.calc_table.setHorizontalHeaderItem(4, item)
        self.calc_table.horizontalHeader().setCascadingSectionResizes(False)
        self.calc_table.horizontalHeader().setSortIndicatorShown(False)
        self.calc_table.horizontalHeader().setStretchLastSection(False)
        self.calc_table.verticalHeader().setVisible(True)
        self.calc_table.verticalHeader().setStretchLastSection(False)
        self.addLineButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addLineButton.setGeometry(QtCore.QRect(90, 610, 101, 41))
        self.addLineButton.setStyleSheet("")
        self.addLineButton.setObjectName("addLineButton")
        self.send_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(400, 640, 101, 41))
        self.send_button.setStyleSheet("")
        self.send_button.setObjectName("send_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Faktura do PDF"))
        self.label_12.setText(_translate("MainWindow", "Faktura č."))
        self.label_14.setText(_translate("MainWindow", "Tvorba Faktury"))
        self.label_10.setText(_translate("MainWindow", "Dodavatel"))
        self.label_17.setText(_translate("MainWindow", "Ulice"))
        self.label_23.setText(_translate("MainWindow", "Město"))
        self.label_26.setText(_translate("MainWindow", "PSČ"))
        self.label_27.setText(_translate("MainWindow", "IČO"))
        self.label_28.setText(_translate("MainWindow", "DIČ"))
        self.label_2.setText(_translate("MainWindow", "Bankovní účet"))
        self.label_3.setText(_translate("MainWindow", "Datum vystavení"))
        self.label.setText(_translate("MainWindow", "Datum splatnosti"))
        self.label_4.setText(_translate("MainWindow", "Způsob úhrady"))
        self.payment_method.setText(_translate("MainWindow", "Převodem"))
        self.label_11.setText(_translate("MainWindow", "Odběratel"))
        self.label_18.setText(_translate("MainWindow", "Ulice"))
        self.label_24.setText(_translate("MainWindow", "Město"))
        self.label_29.setText(_translate("MainWindow", "PSČ"))
        self.label_30.setText(_translate("MainWindow", "IČO"))
        self.label_31.setText(_translate("MainWindow", "DIČ"))
        self.calc_table.setSortingEnabled(False)
        item = self.calc_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Název"))
        item = self.calc_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Množství"))
        item = self.calc_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jedn. cena"))
        item = self.calc_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sleva"))
        item = self.calc_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cena"))
        self.addLineButton.setText(_translate("MainWindow", "Přidat řádek"))
        self.send_button.setText(_translate("MainWindow", "Vytvořit Fakturu"))
